### ISSUE TITLE
503 on the UI!!!! :sad-parrot:

### ISSUE THREAD

**Issue by mcampbell6** [parrotify/parrotify.github.io#6]
I went to make a parrot of my coworker and I'm getting a 503 in the console
<img width="414" alt="screen shot 2017-10-31 at 6 04 45 pm" src="https://user-images.githubusercontent.com/16974851/32251161-30fc950c-be66-11e7-8ce8-bb79c3691e21.png">

**Comment by Omlahid** [comment]
Yes, sorry about that :(

It should be back by now. This is an issue with heroku with the PPaaS backend.

Essentially, the backend is up for a set amount of hours a month, and goes to sleep after 30 minutes of inactivity.

We're being victims of our own popularity I'm afraid.

**Comment by francoislg** [comment]
Our engineers are hard at work providing 99.99% availability and have fixed the issue yesterday at midnight.

Be sure to take note of the complete period of time from which your Parrots have been affected. 

You can then fill an SLA request with our Finances Department.

**Comment by 7thsanctum** [comment]
Party parrot service looks like its down again. :( :( :(

**Comment by francoislg** [comment]
It will be back tomorrow

**Comment by Omlahid** [comment]
Party Parrot is back, and we've ensured that it will stay up longer than before.
Closing this issue. Feel free to open a new one if you notice anything wrong.
